### ISSUE TITLE
How to work with `FileDescriptor`?

### ISSUE THREAD

**Issue by zhuhaow** [CharlesJS/SwiftyXPC#1]
FIrst of all, this framework is awesome! Apple should adopt the library as the official SDK (so they can also fixing the non type safe interface currently we are using).

I'm wondering what is the correct way to handle `FileDescriptor`. 

The problem is, the current API only allows us to return a response, where the fd is not sent yet so we cannot close it immediately (or in defer). However, there is no way to know when the response is sent (or queued) so we cannot close the fd properly.

If we are dealing with `xpc_fd_create` directly, then it is quite easy as it calls `dup` internally and managed the owned fd afterwards. I think we also need to do similar things using `XPCFileDescriptor` (even for 12.0+). `XPCFileDescriptor` should own the fd and close it after calling `xpc_fd_create`. User can still use `FileDescriptor` as long as they want to close the fd themselves.

**Comment by zhuhaow** [comment]
My current implementation would leak fd somewhere.

Given my current implementation (which has the PR #2 applied), https://github.com/zhuhaow/Specht2/blob/main/app/me.zhuhaow.Specht2.proxy-helper/Server.swift#L71-L85, I can verify:

1. The fd is leaked at the XPC Service side. After I close the fd on client side I can only fully close the fd by terminating the service, but If I terminate the service first I can successfully fully close the fd on client side.
2. The fd is not dupped anywhere before the method returns since if I close the fd immediately after I get the fd there won't be any leak.

But the implementation is so simple I really can't figure out where the leak would happen other than `xpc_create_fd`.

Any ideals?

**Comment by zhuhaow** [comment]
I can narrow the leak down to `XPCEncoder`

```swift
internal class MessageHandler {
        typealias RawHandler = ((XPCConnection, xpc_object_t) async throws -> xpc_object_t)
        let closure: RawHandler
        let requestType: Codable.Type
        let responseType: Codable.Type

        init<Request: Codable, Response: Codable>(closure: @escaping (XPCConnection, Request) async throws -> Response) {
            self.requestType = Request.self
            self.responseType = Response.self

            self.closure = { connection, event in
                guard let body = xpc_dictionary_get_value(event, MessageKeys.body) else {
                    throw Error.missingMessageBody
                }

                let request = try XPCDecoder().decode(type: Request.self, from: body)
                let response = try await closure(connection, request)
                // throw error here won't leak
                let encoded = try XPCEncoder().encode(response) 
                // throw error here would leak
                return encoded
            }
        }
    }
```

**Comment by CharlesJS** [comment]
Can you post a minimal project that reproduces the leak so I can try to investigate this myself? Thanks!

**Comment by zhuhaow** [comment]
Here is an example. https://github.com/zhuhaow/leak-demo

Since it not easy to track the lifetime of fd, I use a pipe. The basic idea is if the write fd is closed, the read would get EOF. However, the read side won't get EOF unless we kill the server process to release all fd there.

Note it's using my fork with #2 applied, otherwise we don't have anyway to close the sent fd after it's sent.

**Comment by CharlesJS** [comment]
There was a reference cycle. It wasn't just leaking a file descriptor, it was leaking the whole encoder 😬 

This should be fixed now, and your branch should no longer leak if you rebase it against latest `main`.

I will look at the PR now.
