### ISSUE TITLE
Example code snippet / question

### ISSUE THREAD

**Issue by ghost** [CharlesJS/SwiftyXPC#3]
Thanks a ton for your work on this. From what I've been able to understand, this looks like a massive improvement on doing this via the `NSXPCConnection` route. 

---

What exactly would a simple XPC Service/client (macOS application) look like?

Right now I have the `main.swift` file within an XPC Service project within the macOS app. What would be the best/most appropriate way to structure the service there that (for example) accepts a string from a client and returns it capitalized via its response?

On the client side, what I imagine it would look like is that you'd setup the connection (in a struct?) and then activate the connection in `applicationDidFinishLaunching` within the `AppDelegate` but I'm not sure and was hoping to get some guidance on that.

**Comment by CharlesJS** [comment]
Hey, thanks for your interest! I've just added a minimal example app demonstrating how to set up a basic XPC service.

**Comment by ghost** [comment]
Appreciate it! Thank you @CharlesJS.
