### ISSUE TITLE
Question about interfacing with the client from the service 

### ISSUE THREAD

**Issue by stevebegin** [CharlesJS/SwiftyXPC#4]
Hey, thank you very much for this awesome project! It's super modern, amazingly simple, and just works like a charm!

I found the example you provided to be very helpful, but I'm currently struggling to figure out how to make the service communicate with the client. 

Would you be able to help me out with this and maybe show me how to do the equivalent of what I'm trying to achieve with NSXPCConnection? 

`
let connection = NSXPCConnection(serviceName: xpcServiceLabel)
connection.exportedObject = self
connection.exportedInterface = NSXPCInterface(with: ClientProtocol.self)
` 

Thanks in advance!

**Comment by CharlesJS** [comment]
Hi Steve! This can be done by creating an anonymous `XPCListener` and then sending its `.endpoint` over the connection. The process on the other side can then build a new `XPCConnection` from the endpoint and send messages to it.

I've just added a rudimentary example of how to do this to the example app. It simulates a long-running process that periodically sends progress indications back to the parent process. Check it out for a simple example of how to do the sort of thing you're asking about.
