### ISSUE TITLE
How can I have multiple function parameters?

### ISSUE THREAD

**Issue by lockieluke** [CharlesJS/SwiftyXPC#7]
Message Handler declaration:
<img width="1015" alt="image" src="https://github.com/CharlesJS/SwiftyXPC/assets/25424409/95cc59b0-5d08-4ea6-9785-5bd4b4052e28">

Implementation:
<img width="571" alt="image" src="https://github.com/CharlesJS/SwiftyXPC/assets/25424409/c340be53-3f07-4d7f-9a01-88031059a81b">

**Comment by CharlesJS** [comment]
The most straightforward way to do this is to create a struct in your shared code:

```swift
public struct Timestamps: Codable {
    public let start: Int64
    public let end: Int64
}
```

and then have `rpcSetActivityTimestamps` take that as its second parameter.

Alternatively, you can use standard collections like arrays or dictionaries, as long as they conform to `Codable`.

**Comment by lockieluke** [comment]
Damn thanks for the crazy fast reply, great library btw!  I’ll try this when I have time tomorrow
